wx:
  appServers:
      limaila:
        appId: wx42950b6a4a337305
        appSecret: 80533c6ffee3f573fca89ec23f42e1e4
        appToken: limaila

logging:
  config: classpath:application-logback.xml
  path: /data/logs
  level:
    root: debug
server:
  servlet:
    context-path: ${spring.application.name}
  port: 11080
