spring:
  profiles:
    active: dev
  application:
    name: limaila-weixin-service
  redis:
    # Redis服务器地址
    host: www.limaila.com
    # Redis服务器端口
    port: 6379
    # Redis服务器密码
    password: hxc
    # Redis数据库索引（默认为0）
    database: 0
#    jedis:
#      pool:
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 8
#        # 连接池中的最大空闲连接
#        max-idle: 8
#        # 连接池中的最小空闲连接
#        min-idle: 0
#    # 连接超时时间（毫秒）
#    timeout: 0ms
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: 1ms
  cache:
    type: redis
